clone_depth: 5

environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

cache:
  - node_modules

install:
  - ps: Install-Product node 8 x64
  - npm install -g npm vsce
  - npm install >> log.txt

build_script:
  - npm run compile

artifacts:
  - path: '**\*.vsix'
    name: quickTask.vsix

test_script:
  - node --version
  - npm run test

deploy:
  release: quickTask-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: ffabbc4a8f89437e9a4e147a13755aae6a434d58
  artifact: /.*\.vsix/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
